inference:
  device: mps
  fps: 25
  batch_size: 2
  sadtalker_checkpoint_path: ./pretrained_models/sadtalker/SadTalker_V0.0.2_256.safetensors
  preprocess:
    use_blink: True
    speech_rate: 16000
    syncnet_mel_step_size: 16
    liveportrait_input_shape: 256
    sadtalker_preprocesser_cfg:
      pic_size: 256
      model_path: ./pretrained_models/sadtalker
      lm3d_mat_path: ./src/utils/preprocess/
  audio2coeff:
    flag_exp: True
    flag_pose: False
    audio2pose_cfg:
      cvae_cfg:
        seq_len: 32
        latent_size: 64
        audio_emb_in_size: 512
        audio_emb_out_size: 6
        encoder_layer_sizes: [192, 128]
        decoder_layer_sizes: [128, 192]
        num_classes: 46
  map2lp:
    semantic_radius: 14
    mappingnet_model_path: ./pretrained_models/mappingnet_basic_64inp_onlylip.pt #mappingnet_basic_70inp_nofcnoscale.pt #mappingnet_basic_onlyexp_64inp_epoch00035.pt
    mappingnet_cfg: 
      coeff_nc: 64
      descriptor_nc: 1024
      layer: 3
      num_kp: 6
      num_bins: 66
  lp_render:
    driving_smooth_observation_variance: 3e-7
    liveportrait_cfg:
      models_config: ./src/utils/lp_render/models.yaml
      checkpoint_F: ./pretrained_models/liveportrait/base_models/appearance_feature_extractor.pth
      checkpoint_M: ./pretrained_models/liveportrait/base_models/motion_extractor.pth
      checkpoint_W: ./pretrained_models/liveportrait/base_models/warping_module.pth
      checkpoint_G: ./pretrained_models/liveportrait/base_models/spade_generator.pth
      checkpoint_S: ./pretrained_models/liveportrait/retargeting_models/stitching_retargeting_module.pth
      flag_use_half_precision: False
      mask_crop_path: ./src/utils/lp_render/mask_template.png
      lip_array_pkl_path: ./src/utils/lp_render/lip_array.pkl
      driving_multiplier: 1.0
    synthetic_headpose_generation_cfg:
      window_size: 7
      threshold: 0.02

train:
  checkpoint_save_path: /mnt/ckpts
  logging_save_path: /mnt/logs
  model_cfg:
    device: mps
    batch_size: 64
    num_workers: 6
    learning_rate: 2e-4
    train_dataset_folder_path: /mnt/train
    val_dataset_folder_path: /mnt/val
    dataset_cfg:
      semantic_radius: 14
      input_size: 256
    motionextraction_cfg:
      models_config_path: ./src/utils/lp_render/models.yaml
      motion_extractor_checkpoint_path: ./pretrained_models/liveportrait/base_models/motion_extractor.pth
    mappingnet_cfg: 
      coeff_nc: 64
      descriptor_nc: 1024
      layer: 3
      num_kp: 6
      num_bins: 66
    loss_cfg:
      reduction: mean

download:
  target_fps: 25
  dataset_folder_path: /mnt/train
  raw_folder_path: /mnt/raw_train

threedmm:
  device: mps
  fps: 25
  batch_size: 28
  dataset_folder_path: /mnt/train
  raw_folder_path: /mnt/raw_train
  sadtalker_checkpoint_path: ./pretrained_models/sadtalker/SadTalker_V0.0.2_256.safetensors
  preprocesser_cfg:
    pic_size: 256
    model_path: ./pretrained_models/sadtalker
    frontality_threshold: 50
    lm3d_mat_path: ./src/utils/preprocess
