inference:
  device: mps
  fps: 25
  batch_size: 2
  sadtalker_checkpoint_path: ../liveportrait_talker_dev/pretrained_models/sadtalker/SadTalker_V0.0.2_256.safetensors
  preprocess:
    use_blink: True
    speech_rate: 16000
    syncnet_mel_step_size: 16
    liveportrait_input_shape: 256
    sadtalker_preprocesser_cfg:
      pic_size: 256
      model_path: ../liveportrait_talker_dev/pretrained_models/sadtalker
      lm3d_mat_path: ../liveportrait_talker_dev/pretrained_models/sadtalker
  audio2coeff:
    flag_exp: True
    flag_pose: True
    audio2pose_cfg:
      cvae_cfg:
        seq_len: 32
        latent_size: 64
        audio_emb_in_size: 512
        audio_emb_out_size: 6
        encoder_layer_sizes: [192, 128]
        decoder_layer_sizes: [128, 192]
        num_classes: 46
  map2lp:
    semantic_radius: 14
    mappingnet_model_path: ../liveportrait_talker_dev/pretrained_models/mappingnet_basic_70inp_nofcnoscale.pt #mappingnet_basic_onlyexp_64inp_epoch00035.pt
    mappingnet_cfg: 
      coeff_nc: 70
      descriptor_nc: 1024
      layer: 3
      num_kp: 21
      num_bins: 66
  lp_render:
    liveportrait_cfg:
      models_config: ../liveportrait_talker_dev/pretrained_models/liveportrait/models.yaml
      checkpoint_F: ../liveportrait_talker_dev/pretrained_models/liveportrait/base_models/appearance_feature_extractor.pth
      checkpoint_M: ../liveportrait_talker_dev/pretrained_models/liveportrait/base_models/motion_extractor.pth
      checkpoint_W: ../liveportrait_talker_dev/pretrained_models/liveportrait/base_models/warping_module.pth
      checkpoint_G: ../liveportrait_talker_dev/pretrained_models/liveportrait/base_models/spade_generator.pth
      checkpoint_S: ../liveportrait_talker_dev/pretrained_models/liveportrait/retargeting_models/stitching_retargeting_module.pth
      flag_use_half_precision: False
      mask_crop_path: ../liveportrait_talker_dev/pretrained_models/liveportrait/mask_template.png
      lip_array_pkl_path: ../liveportrait_talker_dev/pretrained_models/liveportrait/lip_array.pkl
      driving_multiplier: 1.0
