inference:
  device: mps
  fps: 25
  sadtalker_checkpoint_path: ../liveportrait_talker_dev/pretrained_models/sadtalker/SadTalker_V0.0.2_256.safetensors
  preprocess:
    use_blink: True
    speech_rate: 16000
    syncnet_mel_step_size: 16
    sadtalker_preprocesser_cfg:
      pic_size: 256
      model_path: ../liveportrait_talker_dev/pretrained_models/sadtalker
      frontality_threshold: 50
      lm3d_mat_path: ../liveportrait_talker_dev/pretrained_models/sadtalker